// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loomchain/registry/registry.proto

package registry

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              *types.Address `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Owner                *types.Address `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_8f33b09e6c22f9ce, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Record) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Record) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "Record")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loomchain/registry/registry.proto", fileDescriptor_registry_8f33b09e6c22f9ce)
}

var fileDescriptor_registry_8f33b09e6c22f9ce = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xcf, 0xcf, 0xcd, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0x06, 0xb3, 0x93, 0x33, 0x12, 0x33, 0xf3, 0xf4, 0x8b, 0x52, 0xd3, 0x33, 0x8b, 0x4b,
	0x8a, 0x2a, 0xe1, 0x0c, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x29, 0x03, 0x1c, 0x3a, 0xd3, 0xf3,
	0x75, 0x41, 0x5c, 0xfd, 0x92, 0xca, 0x82, 0xd4, 0x62, 0x08, 0x09, 0xd1, 0xa1, 0x94, 0xc0, 0xc5,
	0x16, 0x94, 0x9a, 0x9c, 0x5f, 0x94, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x29, 0x71, 0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5,
	0x16, 0x17, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x71, 0xe8, 0x39, 0x42, 0xf8, 0x41, 0x30,
	0x09, 0x21, 0x39, 0x2e, 0xd6, 0xfc, 0xf2, 0xbc, 0xd4, 0x22, 0x09, 0x66, 0x34, 0x15, 0x10, 0xe1,
	0x24, 0x36, 0xb0, 0x45, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x51, 0x62, 0x0c, 0xd6,
	0x00, 0x00, 0x00,
}
