run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - gocyclo
    - golint
    - maligned
    - errcheck
    - staticcheck
    - interfacer
    - unconvert
    - goconst
    - unparam
    - nakedret
    - gochecknoglobals
    - gocritic
    - gochecknoinits
    - scopelint
    - stylecheck
    - dupl
    - prealloc # re-enable later when we quash the more annoying stuff
linters-settings:
#   govet:
#     check-shadowing: true
#   golint:
#     min-confidence: 0
#   gocyclo:
#     min-complexity: 10
#   maligned:
#     suggest-new: true
#   dupl:
#     threshold: 100
#   goconst:
#     min-len: 2
#     min-occurrences: 2
#   depguard:
#     list-type: blacklist
#     packages:
#       # logging is allowed only by logutils.Log, logrus
#       # is allowed to use only in logutils package
#       - github.com/sirupsen/logrus
#   misspell:
#     locale: US
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 200 # should be 120, but need to fix the more important linter errors first...
#   goimports:
#     local-prefixes: github.com/golangci/golangci-lint
#   gocritic:
#     enabled-tags:
#       - performance
#       - style
#       - experimental
#     disabled-checks:
#       - wrapperFunc
#       - commentFormatting # https://github.com/go-critic/go-critic/issues/755

