// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vm.proto

/*
Package vm is a generated protocol buffer package.

It is generated from these files:
	vm.proto

It has these top-level messages:
	DeployTx
	SendTx
	Event
	Events
*/
package vm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployTx struct {
	// Code plus input arguments to constructor
	Input []byte `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *DeployTx) Reset()                    { *m = DeployTx{} }
func (m *DeployTx) String() string            { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()               {}
func (*DeployTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type SendTx struct {
	// Contract address
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Function name plus input arguments
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *SendTx) Reset()                    { *m = SendTx{} }
func (m *SendTx) String() string            { return proto.CompactTextString(m) }
func (*SendTx) ProtoMessage()               {}
func (*SendTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendTx) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SendTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type Event struct {
	// address of the contract that generated the event
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// list of topics provided by the contract.
	Topics [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// supplied by the contract, usually ABI-encoded
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Event) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Event) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Events struct {
	Events []*Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *Events) Reset()                    { *m = Events{} }
func (m *Events) String() string            { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()               {}
func (*Events) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*SendTx)(nil), "SendTx")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Events)(nil), "Events")
}

func init() { proto.RegisterFile("vm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0xcb, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2, 0x70, 0x49, 0x2d, 0xc8, 0xc9, 0xaf, 0x0c, 0xa9,
	0x10, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x82, 0x70, 0x94, 0x2c, 0xb8, 0xd8, 0x82, 0x53, 0xf3, 0x52, 0x42, 0x2a, 0x84, 0x24, 0xb8, 0xd8,
	0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0xa1, 0x2a, 0x60, 0x5c, 0x84, 0x4e, 0x26, 0x64, 0x9d,
	0xbe, 0x5c, 0xac, 0xae, 0x65, 0xa9, 0x79, 0x25, 0x78, 0x34, 0x8a, 0x71, 0xb1, 0x95, 0xe4, 0x17,
	0x64, 0x26, 0x17, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0xf0, 0x04, 0x41, 0x79, 0x42, 0x42, 0x5c, 0x2c,
	0x29, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x60, 0xe5, 0x60, 0xb6, 0x92, 0x06, 0x17, 0x1b, 0xd8, 0xb8,
	0x62, 0x21, 0x39, 0x2e, 0xb6, 0x54, 0x30, 0x4b, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x4d,
	0x0f, 0x2c, 0x11, 0x04, 0x15, 0x4d, 0x62, 0x03, 0xfb, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x77, 0x09, 0x09, 0x35, 0xe7, 0x00, 0x00, 0x00,
}
