// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vm.proto

/*
Package vm is a generated protocol buffer package.

It is generated from these files:
	vm.proto

It has these top-level messages:
	DeployTx
	SendTx
*/
package vm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployTx struct {
	// Code plus input arguments to constructor
	Input []byte `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *DeployTx) Reset()                    { *m = DeployTx{} }
func (m *DeployTx) String() string            { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()               {}
func (*DeployTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type SendTx struct {
	// Contract address
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Function name plus input arguments
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *SendTx) Reset()                    { *m = SendTx{} }
func (m *SendTx) String() string            { return proto.CompactTextString(m) }
func (*SendTx) ProtoMessage()               {}
func (*SendTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendTx) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SendTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func init() {
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*SendTx)(nil), "SendTx")
}

func init() { proto.RegisterFile("vm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0xcb, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2, 0x70, 0x49, 0x2d, 0xc8, 0xc9, 0xaf, 0x0c, 0xa9,
	0x10, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x82, 0x70, 0x94, 0x2c, 0xb8, 0xd8, 0x82, 0x53, 0xf3, 0x52, 0x42, 0x2a, 0x84, 0x24, 0xb8, 0xd8,
	0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0xa1, 0x2a, 0x60, 0x5c, 0x84, 0x4e, 0x26, 0x24, 0x9d,
	0x49, 0x6c, 0x60, 0x2b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x45, 0xc5, 0xde, 0x6e,
	0x00, 0x00, 0x00,
}
