[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call transfer {{index $.AccountAddressList 1}} 20 -k {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["120000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["800000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call list_witnesses"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call transfer dpos 90 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["10000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance dpos"
  Condition = "contains"
  Expected = ["90000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call register_candidate {{index $.AccountPubKeyList 0}} -k {{index $.AccountPrivKeyPathList 0}}"

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call vote {{index $.AccountAddressList 0}} 21 -k {{index $.AccountPrivKeyPathList 0}}"

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call list_witnesses"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call elect -k {{index $.AccountPrivKeyPathList 0}}"

# the last round witnesses list would be paid for services
[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
  Condition = "contains"
  Expected = ["10000000000000000000"]

# # DPOS remaing after paying for 1 nodes
[[TestCases]]
  Dir = ""
  RunCmd = "example-cli call balance dpos"
  Condition = "contains"
  Expected = ["80000000000000000000"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call list_witnesses"
#   Condition = "contains"
#   Expected = ["{{index $.AccountPubKeyList 0}}", "{{index $.AccountPubKeyList 1}}", "{{index $.AccountPubKeyList 2}}"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
#   Condition = "contains"
#   Expected = ["10000000000000000000"]


# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
#   Condition = "contains"
#   Expected = ["12000000000000000000"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
#   Condition = "contains"
#   Expected = ["8000000000000000000"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call elect -k {{index $.AccountPrivKeyPathList 0}}"
#   Condition = ""


# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
#   Condition = "contains"
#   Expected = ["20000000000000000000"]


# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
#   Condition = "contains"
#   Expected = ["13000000000000000000"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
#   Condition = "contains"
#   Expected = ["9000000000000000000"]

# [[TestCases]]
#   Dir = ""
#   RunCmd = "example-cli call balance dpos"
#   Condition = "contains"
#   Expected = ["0"]