// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vm/vm.proto

/*
Package vm is a generated protocol buffer package.

It is generated from these files:
	vm/vm.proto

It has these top-level messages:
	DeployTx
	SendTx
*/
package vm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import loom "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployTx struct {
	To   *loom.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Code []byte        `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *DeployTx) Reset()                    { *m = DeployTx{} }
func (m *DeployTx) String() string            { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()               {}
func (*DeployTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployTx) GetTo() *loom.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DeployTx) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type SendTx struct {
	To *loom.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
}

func (m *SendTx) Reset()                    { *m = SendTx{} }
func (m *SendTx) String() string            { return proto.CompactTextString(m) }
func (*SendTx) ProtoMessage()               {}
func (*SendTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendTx) GetTo() *loom.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*SendTx)(nil), "SendTx")
}

func init() { proto.RegisterFile("vm/vm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xcb, 0xd5, 0x2f,
	0xcb, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0xca, 0xc9, 0xcf, 0x87, 0xb2, 0x95, 0x2c,
	0xb8, 0x38, 0x5c, 0x52, 0x0b, 0x72, 0xf2, 0x2b, 0x43, 0x2a, 0x84, 0x24, 0xb8, 0x98, 0x4a, 0xf2,
	0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x38, 0xf4, 0x1c, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b,
	0x83, 0x98, 0x4a, 0xf2, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x14, 0x18,
	0x35, 0x78, 0x82, 0xc0, 0x6c, 0x25, 0x25, 0x2e, 0xb6, 0xe0, 0xd4, 0xbc, 0x14, 0x7c, 0xfa, 0x92,
	0xd8, 0xc0, 0x96, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x25, 0x95, 0x16, 0xf6, 0x7f, 0x00,
	0x00, 0x00,
}
