// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loom/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loom/auth/auth.proto

It has these top-level messages:
	SignedTx
*/
package auth

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SignedTx struct {
	Inner     []byte `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *SignedTx) Reset()                    { *m = SignedTx{} }
func (m *SignedTx) String() string            { return proto.CompactTextString(m) }
func (*SignedTx) ProtoMessage()               {}
func (*SignedTx) Descriptor() ([]byte, []int) { return fileDescriptorAuth, []int{0} }

func (m *SignedTx) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *SignedTx) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedTx) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*SignedTx)(nil), "SignedTx")
}

func init() { proto.RegisterFile("github.com/loomnetwork/loom/auth/auth.proto", fileDescriptorAuth) }

var fileDescriptorAuth = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xcf, 0xcf, 0xcd, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0x06, 0xb3, 0xf5, 0x13, 0x4b, 0x4b, 0x32, 0xc0, 0x84, 0x5e, 0x41, 0x51, 0x7e, 0x49,
	0xbe, 0x52, 0x2c, 0x17, 0x47, 0x70, 0x66, 0x7a, 0x5e, 0x6a, 0x4a, 0x48, 0x85, 0x90, 0x08, 0x17,
	0x6b, 0x66, 0x5e, 0x5e, 0x6a, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x84, 0x23, 0x24,
	0xc3, 0xc5, 0x59, 0x9c, 0x99, 0x9e, 0x97, 0x58, 0x52, 0x5a, 0x94, 0x2a, 0xc1, 0x04, 0x96, 0x41,
	0x08, 0x08, 0xc9, 0x72, 0x71, 0x15, 0x94, 0x26, 0xe5, 0x64, 0x26, 0xc7, 0x67, 0xa7, 0x56, 0x4a,
	0x30, 0x43, 0xa4, 0x21, 0x22, 0xde, 0xa9, 0x95, 0x49, 0x6c, 0x60, 0x5b, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf7, 0x65, 0x77, 0xe2, 0x94, 0x00, 0x00, 0x00,
}
