// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loom/contract/contract.proto

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loom/contract/contract.proto

It has these top-level messages:
	MessageTx
	DeployTx
	CallTx
*/
package contract

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MessageTx struct {
	To   *types.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From *types.Address `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Data []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MessageTx) Reset()                    { *m = MessageTx{} }
func (m *MessageTx) String() string            { return proto.CompactTextString(m) }
func (*MessageTx) ProtoMessage()               {}
func (*MessageTx) Descriptor() ([]byte, []int) { return fileDescriptorContract, []int{0} }

func (m *MessageTx) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MessageTx) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeployTx struct {
	Name        string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string         `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Upgradeable bool           `protobuf:"varint,3,opt,name=upgradeable,proto3" json:"upgradeable,omitempty"`
	Input       []byte         `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Code        []byte         `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Owner       *types.Address `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
}

func (m *DeployTx) Reset()                    { *m = DeployTx{} }
func (m *DeployTx) String() string            { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()               {}
func (*DeployTx) Descriptor() ([]byte, []int) { return fileDescriptorContract, []int{1} }

func (m *DeployTx) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployTx) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployTx) GetUpgradeable() bool {
	if m != nil {
		return m.Upgradeable
	}
	return false
}

func (m *DeployTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *DeployTx) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DeployTx) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type CallTx struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *CallTx) Reset()                    { *m = CallTx{} }
func (m *CallTx) String() string            { return proto.CompactTextString(m) }
func (*CallTx) ProtoMessage()               {}
func (*CallTx) Descriptor() ([]byte, []int) { return fileDescriptorContract, []int{2} }

func (m *CallTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageTx)(nil), "MessageTx")
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*CallTx)(nil), "CallTx")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loom/contract/contract.proto", fileDescriptorContract)
}

var fileDescriptorContract = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4e, 0xb4, 0x30,
	0x10, 0xc7, 0x03, 0x1f, 0xf0, 0xc1, 0xac, 0xa7, 0xc6, 0x43, 0x63, 0xcc, 0x86, 0x70, 0xda, 0x8b,
	0x6c, 0xe2, 0x3e, 0x81, 0xd1, 0xab, 0x17, 0x42, 0xe2, 0xb9, 0xc0, 0x88, 0x44, 0xe8, 0x90, 0x76,
	0x70, 0xd9, 0xf7, 0xf1, 0x41, 0x0d, 0x25, 0xea, 0x66, 0x0f, 0x5e, 0x9a, 0xdf, 0xfc, 0x3b, 0xfd,
	0xcd, 0xa4, 0x70, 0x68, 0x3b, 0x7e, 0x9b, 0xaa, 0xbc, 0xa6, 0x61, 0xdf, 0x13, 0x0d, 0x1a, 0xf9,
	0x48, 0xe6, 0xdd, 0xf1, 0xbe, 0x26, 0xcd, 0x46, 0xd5, 0xfc, 0x03, 0xf9, 0x68, 0x88, 0xe9, 0xe6,
	0xee, 0xaf, 0x47, 0x7c, 0x1a, 0xd1, 0xae, 0xe7, 0xda, 0x9e, 0xbd, 0x40, 0xf2, 0x8c, 0xd6, 0xaa,
	0x16, 0xcb, 0x59, 0x48, 0xf0, 0x99, 0xa4, 0x97, 0x7a, 0xbb, 0xcd, 0x7d, 0x9c, 0x3f, 0x34, 0x8d,
	0x41, 0x6b, 0x0b, 0x9f, 0x49, 0xdc, 0x42, 0xf0, 0x6a, 0x68, 0x90, 0xfe, 0xc5, 0x9d, 0x4b, 0x85,
	0x80, 0xa0, 0x51, 0xac, 0xe4, 0xbf, 0xd4, 0xdb, 0x5d, 0x15, 0x8e, 0xb3, 0x4f, 0x0f, 0xe2, 0x27,
	0x1c, 0x7b, 0x3a, 0x95, 0xf3, 0xd2, 0xa0, 0xd5, 0x80, 0x4e, 0x9d, 0x14, 0x8e, 0x85, 0x84, 0xff,
	0x1f, 0x68, 0x6c, 0x47, 0xda, 0x59, 0x93, 0xe2, 0xbb, 0x14, 0x29, 0x6c, 0xa6, 0xb1, 0x35, 0xaa,
	0x41, 0x55, 0xf5, 0xe8, 0xac, 0x71, 0x71, 0x1e, 0x89, 0x6b, 0x08, 0x3b, 0x3d, 0x4e, 0x2c, 0x03,
	0x37, 0x71, 0x2d, 0x96, 0x29, 0x35, 0x35, 0x28, 0xc3, 0x75, 0x8d, 0x85, 0xc5, 0x16, 0x42, 0x3a,
	0x6a, 0x34, 0x32, 0xba, 0xd8, 0x7c, 0x8d, 0xb3, 0x2d, 0x44, 0x8f, 0xaa, 0xef, 0xcb, 0xf9, 0xd7,
	0xe9, 0x9f, 0x39, 0xab, 0xc8, 0x7d, 0xd3, 0xe1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xb9, 0x64,
	0x54, 0x8c, 0x01, 0x00, 0x00,
}
