// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loomchain/builtin/plugins/karma/types/types.proto

/*
Package karma is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loomchain/builtin/plugins/karma/types/types.proto

It has these top-level messages:
	KarmaParams
	KarmaParamsValidator
	KarmaParamsValidatorNewMaxKarma
	KarmaParamsValidatorNewOracle
	KarmaParamsMutableValidator
	KarmaConfig
	KarmaSource
	KarmaState
	KarmaStateUser
	KarmaStateKeyUser
	KarmaInitRequest
	KarmaUserToken
	KarmaTotal
*/
package karma

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type KarmaParams struct {
	MutableOracle bool               `protobuf:"varint,1,opt,name=mutable_oracle,json=mutableOracle,proto3" json:"mutable_oracle,omitempty"`
	MaxKarma      int64              `protobuf:"varint,2,opt,name=max_karma,json=maxKarma,proto3" json:"max_karma,omitempty"`
	Oracle        *types.Address     `protobuf:"bytes,3,opt,name=Oracle" json:"Oracle,omitempty"`
	Sources       map[string]int64   `protobuf:"bytes,4,rep,name=sources" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Validators    []*types.Validator `protobuf:"bytes,5,rep,name=validators" json:"validators,omitempty"`
}

func (m *KarmaParams) Reset()                    { *m = KarmaParams{} }
func (m *KarmaParams) String() string            { return proto.CompactTextString(m) }
func (*KarmaParams) ProtoMessage()               {}
func (*KarmaParams) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *KarmaParams) GetMutableOracle() bool {
	if m != nil {
		return m.MutableOracle
	}
	return false
}

func (m *KarmaParams) GetMaxKarma() int64 {
	if m != nil {
		return m.MaxKarma
	}
	return 0
}

func (m *KarmaParams) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

func (m *KarmaParams) GetSources() map[string]int64 {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *KarmaParams) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type KarmaParamsValidator struct {
	Params    *KarmaParams     `protobuf:"bytes,1,opt,name=Params" json:"Params,omitempty"`
	Validator *types.Validator `protobuf:"bytes,2,opt,name=Validator" json:"Validator,omitempty"`
	Oracle    *types.Address   `protobuf:"bytes,3,opt,name=Oracle" json:"Oracle,omitempty"`
}

func (m *KarmaParamsValidator) Reset()                    { *m = KarmaParamsValidator{} }
func (m *KarmaParamsValidator) String() string            { return proto.CompactTextString(m) }
func (*KarmaParamsValidator) ProtoMessage()               {}
func (*KarmaParamsValidator) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *KarmaParamsValidator) GetParams() *KarmaParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *KarmaParamsValidator) GetValidator() *types.Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *KarmaParamsValidator) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

type KarmaParamsValidatorNewMaxKarma struct {
	MaxKarma  int64            `protobuf:"varint,1,opt,name=max_karma,json=maxKarma,proto3" json:"max_karma,omitempty"`
	Validator *types.Validator `protobuf:"bytes,2,opt,name=Validator" json:"Validator,omitempty"`
}

func (m *KarmaParamsValidatorNewMaxKarma) Reset()         { *m = KarmaParamsValidatorNewMaxKarma{} }
func (m *KarmaParamsValidatorNewMaxKarma) String() string { return proto.CompactTextString(m) }
func (*KarmaParamsValidatorNewMaxKarma) ProtoMessage()    {}
func (*KarmaParamsValidatorNewMaxKarma) Descriptor() ([]byte, []int) {
	return fileDescriptorTypes, []int{2}
}

func (m *KarmaParamsValidatorNewMaxKarma) GetMaxKarma() int64 {
	if m != nil {
		return m.MaxKarma
	}
	return 0
}

func (m *KarmaParamsValidatorNewMaxKarma) GetValidator() *types.Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type KarmaParamsValidatorNewOracle struct {
	NewOracle *types.Address   `protobuf:"bytes,1,opt,name=NewOracle" json:"NewOracle,omitempty"`
	Validator *types.Validator `protobuf:"bytes,2,opt,name=Validator" json:"Validator,omitempty"`
}

func (m *KarmaParamsValidatorNewOracle) Reset()         { *m = KarmaParamsValidatorNewOracle{} }
func (m *KarmaParamsValidatorNewOracle) String() string { return proto.CompactTextString(m) }
func (*KarmaParamsValidatorNewOracle) ProtoMessage()    {}
func (*KarmaParamsValidatorNewOracle) Descriptor() ([]byte, []int) {
	return fileDescriptorTypes, []int{3}
}

func (m *KarmaParamsValidatorNewOracle) GetNewOracle() *types.Address {
	if m != nil {
		return m.NewOracle
	}
	return nil
}

func (m *KarmaParamsValidatorNewOracle) GetValidator() *types.Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type KarmaParamsMutableValidator struct {
	MutableOracle bool             `protobuf:"varint,1,opt,name=mutable_oracle,json=mutableOracle,proto3" json:"mutable_oracle,omitempty"`
	Validator     *types.Validator `protobuf:"bytes,2,opt,name=Validator" json:"Validator,omitempty"`
}

func (m *KarmaParamsMutableValidator) Reset()                    { *m = KarmaParamsMutableValidator{} }
func (m *KarmaParamsMutableValidator) String() string            { return proto.CompactTextString(m) }
func (*KarmaParamsMutableValidator) ProtoMessage()               {}
func (*KarmaParamsMutableValidator) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *KarmaParamsMutableValidator) GetMutableOracle() bool {
	if m != nil {
		return m.MutableOracle
	}
	return false
}

func (m *KarmaParamsMutableValidator) GetValidator() *types.Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type KarmaConfig struct {
	MutableOracle  bool             `protobuf:"varint,1,opt,name=mutable_oracle,json=mutableOracle,proto3" json:"mutable_oracle,omitempty"`
	MaxKarma       int64            `protobuf:"varint,2,opt,name=max_karma,json=maxKarma,proto3" json:"max_karma,omitempty"`
	Oracle         *types.Address   `protobuf:"bytes,3,opt,name=Oracle" json:"Oracle,omitempty"`
	Sources        map[string]int64 `protobuf:"bytes,4,rep,name=sources" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	LastUpdateTime int64            `protobuf:"varint,5,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
}

func (m *KarmaConfig) Reset()                    { *m = KarmaConfig{} }
func (m *KarmaConfig) String() string            { return proto.CompactTextString(m) }
func (*KarmaConfig) ProtoMessage()               {}
func (*KarmaConfig) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *KarmaConfig) GetMutableOracle() bool {
	if m != nil {
		return m.MutableOracle
	}
	return false
}

func (m *KarmaConfig) GetMaxKarma() int64 {
	if m != nil {
		return m.MaxKarma
	}
	return 0
}

func (m *KarmaConfig) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

func (m *KarmaConfig) GetSources() map[string]int64 {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *KarmaConfig) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

type KarmaSource struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reward int64  `protobuf:"varint,2,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (m *KarmaSource) Reset()                    { *m = KarmaSource{} }
func (m *KarmaSource) String() string            { return proto.CompactTextString(m) }
func (*KarmaSource) ProtoMessage()               {}
func (*KarmaSource) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{6} }

func (m *KarmaSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KarmaSource) GetReward() int64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

type KarmaState struct {
	SourceStates   map[string]int64 `protobuf:"bytes,1,rep,name=source_states,json=sourceStates" json:"source_states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	LastUpdateTime int64            `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
}

func (m *KarmaState) Reset()                    { *m = KarmaState{} }
func (m *KarmaState) String() string            { return proto.CompactTextString(m) }
func (*KarmaState) ProtoMessage()               {}
func (*KarmaState) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{7} }

func (m *KarmaState) GetSourceStates() map[string]int64 {
	if m != nil {
		return m.SourceStates
	}
	return nil
}

func (m *KarmaState) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

type KarmaStateUser struct {
	SourceStates map[string]int64 `protobuf:"bytes,1,rep,name=source_states,json=sourceStates" json:"source_states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	User         *types.Address   `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Oracle       *types.Address   `protobuf:"bytes,3,opt,name=Oracle" json:"Oracle,omitempty"`
}

func (m *KarmaStateUser) Reset()                    { *m = KarmaStateUser{} }
func (m *KarmaStateUser) String() string            { return proto.CompactTextString(m) }
func (*KarmaStateUser) ProtoMessage()               {}
func (*KarmaStateUser) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{8} }

func (m *KarmaStateUser) GetSourceStates() map[string]int64 {
	if m != nil {
		return m.SourceStates
	}
	return nil
}

func (m *KarmaStateUser) GetUser() *types.Address {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *KarmaStateUser) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

type KarmaStateKeyUser struct {
	StateKeys []string       `protobuf:"bytes,1,rep,name=state_keys,json=stateKeys" json:"state_keys,omitempty"`
	User      *types.Address `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Oracle    *types.Address `protobuf:"bytes,3,opt,name=Oracle" json:"Oracle,omitempty"`
}

func (m *KarmaStateKeyUser) Reset()                    { *m = KarmaStateKeyUser{} }
func (m *KarmaStateKeyUser) String() string            { return proto.CompactTextString(m) }
func (*KarmaStateKeyUser) ProtoMessage()               {}
func (*KarmaStateKeyUser) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{9} }

func (m *KarmaStateKeyUser) GetStateKeys() []string {
	if m != nil {
		return m.StateKeys
	}
	return nil
}

func (m *KarmaStateKeyUser) GetUser() *types.Address {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *KarmaStateKeyUser) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

type KarmaInitRequest struct {
	Params *KarmaParams `protobuf:"bytes,1,opt,name=Params" json:"Params,omitempty"`
}

func (m *KarmaInitRequest) Reset()                    { *m = KarmaInitRequest{} }
func (m *KarmaInitRequest) String() string            { return proto.CompactTextString(m) }
func (*KarmaInitRequest) ProtoMessage()               {}
func (*KarmaInitRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{10} }

func (m *KarmaInitRequest) GetParams() *KarmaParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type KarmaUserToken struct {
	Owner      *types.Address `protobuf:"bytes,1,opt,name=Owner" json:"Owner,omitempty"`
	TokenCount int64          `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
}

func (m *KarmaUserToken) Reset()                    { *m = KarmaUserToken{} }
func (m *KarmaUserToken) String() string            { return proto.CompactTextString(m) }
func (*KarmaUserToken) ProtoMessage()               {}
func (*KarmaUserToken) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{11} }

func (m *KarmaUserToken) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *KarmaUserToken) GetTokenCount() int64 {
	if m != nil {
		return m.TokenCount
	}
	return 0
}

type KarmaTotal struct {
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *KarmaTotal) Reset()                    { *m = KarmaTotal{} }
func (m *KarmaTotal) String() string            { return proto.CompactTextString(m) }
func (*KarmaTotal) ProtoMessage()               {}
func (*KarmaTotal) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{12} }

func (m *KarmaTotal) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*KarmaParams)(nil), "karma.KarmaParams")
	proto.RegisterType((*KarmaParamsValidator)(nil), "karma.KarmaParamsValidator")
	proto.RegisterType((*KarmaParamsValidatorNewMaxKarma)(nil), "karma.KarmaParamsValidatorNewMaxKarma")
	proto.RegisterType((*KarmaParamsValidatorNewOracle)(nil), "karma.KarmaParamsValidatorNewOracle")
	proto.RegisterType((*KarmaParamsMutableValidator)(nil), "karma.KarmaParamsMutableValidator")
	proto.RegisterType((*KarmaConfig)(nil), "karma.KarmaConfig")
	proto.RegisterType((*KarmaSource)(nil), "karma.KarmaSource")
	proto.RegisterType((*KarmaState)(nil), "karma.KarmaState")
	proto.RegisterType((*KarmaStateUser)(nil), "karma.KarmaStateUser")
	proto.RegisterType((*KarmaStateKeyUser)(nil), "karma.KarmaStateKeyUser")
	proto.RegisterType((*KarmaInitRequest)(nil), "karma.KarmaInitRequest")
	proto.RegisterType((*KarmaUserToken)(nil), "karma.KarmaUserToken")
	proto.RegisterType((*KarmaTotal)(nil), "karma.KarmaTotal")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loomchain/builtin/plugins/karma/types/types.proto", fileDescriptorTypes)
}

var fileDescriptorTypes = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xce, 0xb6, 0xb4, 0xb2, 0xa7, 0x40, 0x60, 0x42, 0xcc, 0x06, 0x44, 0x9a, 0x35, 0xea, 0x86,
	0xc4, 0xad, 0xc1, 0x1b, 0xe1, 0x42, 0x63, 0x88, 0x09, 0x06, 0x11, 0x5d, 0xc1, 0xdb, 0xcd, 0xb4,
	0x1d, 0xcb, 0xa6, 0xbb, 0x33, 0x65, 0x66, 0x96, 0xd2, 0x97, 0xf0, 0xca, 0xf8, 0x3e, 0x3e, 0x89,
	0xaf, 0x62, 0xe6, 0xa7, 0xec, 0x62, 0x4b, 0xa0, 0xe9, 0x8d, 0x37, 0x64, 0xce, 0x37, 0xe7, 0xe7,
	0xfb, 0xce, 0x7c, 0x6c, 0xe1, 0xb0, 0x97, 0xc8, 0xf3, 0xbc, 0x1d, 0x76, 0x58, 0xd6, 0x4a, 0x19,
	0xcb, 0x28, 0x91, 0x43, 0xc6, 0xfb, 0xfa, 0xdc, 0x39, 0xc7, 0x09, 0x6d, 0xb5, 0xf3, 0x24, 0x95,
	0x09, 0x6d, 0x0d, 0xd2, 0xbc, 0x97, 0x50, 0xd1, 0xea, 0x63, 0x9e, 0xe1, 0x96, 0x1c, 0x0d, 0x88,
	0x30, 0x7f, 0xc3, 0x01, 0x67, 0x92, 0xa1, 0x9a, 0xbe, 0xd8, 0x78, 0x79, 0x4b, 0xc3, 0x1e, 0x7b,
	0xa1, 0xc2, 0xc9, 0x42, 0xff, 0x57, 0x05, 0x1a, 0x47, 0xaa, 0xf6, 0x33, 0xe6, 0x38, 0x13, 0xe8,
	0x29, 0xac, 0x64, 0xb9, 0xc4, 0xed, 0x94, 0xc4, 0x8c, 0xe3, 0x4e, 0x4a, 0x3c, 0xa7, 0xe9, 0x04,
	0x8b, 0xd1, 0xb2, 0x45, 0x4f, 0x34, 0x88, 0x36, 0xc1, 0xcd, 0xf0, 0x55, 0xac, 0xa7, 0x7a, 0x95,
	0xa6, 0x13, 0x54, 0xa3, 0xc5, 0x0c, 0x5f, 0xe9, 0x4e, 0xa8, 0x09, 0x75, 0x93, 0xe6, 0x55, 0x9b,
	0x4e, 0xd0, 0xd8, 0x5d, 0x0c, 0xdf, 0x75, 0xbb, 0x9c, 0x08, 0x11, 0x59, 0x1c, 0xed, 0xc1, 0x03,
	0xc1, 0x72, 0xde, 0x21, 0xc2, 0x5b, 0x68, 0x56, 0x83, 0xc6, 0xee, 0x76, 0xa8, 0x5b, 0x85, 0x25,
	0x2a, 0xe1, 0x57, 0x93, 0xf1, 0x9e, 0x4a, 0x3e, 0x8a, 0xc6, 0xf9, 0x68, 0x07, 0xe0, 0x12, 0xa7,
	0x49, 0x17, 0x4b, 0xc6, 0x85, 0x57, 0xd3, 0xd5, 0x10, 0x7e, 0x1b, 0x43, 0x51, 0xe9, 0x76, 0x63,
	0x1f, 0x96, 0xca, 0x4d, 0xd0, 0x2a, 0x54, 0xfb, 0x64, 0xa4, 0x15, 0xb9, 0x91, 0x3a, 0xa2, 0x75,
	0xa8, 0x5d, 0xe2, 0x34, 0x27, 0x56, 0x83, 0x09, 0xf6, 0x2b, 0xaf, 0x1d, 0xff, 0x87, 0x03, 0xeb,
	0x25, 0x36, 0xd7, 0x03, 0xd0, 0x0e, 0xd4, 0x0d, 0xa4, 0xfb, 0x34, 0x76, 0xd1, 0x24, 0xf5, 0xc8,
	0x66, 0xa0, 0x00, 0xdc, 0xeb, 0x42, 0x3d, 0xe2, 0x26, 0xd7, 0xe2, 0xf2, 0xee, 0x9d, 0xf9, 0xe7,
	0xb0, 0x3d, 0x8d, 0xcf, 0x27, 0x32, 0x3c, 0x1e, 0x2f, 0xfe, 0xc6, 0xab, 0x38, 0xff, 0xbc, 0xca,
	0xbd, 0xb9, 0xf8, 0x17, 0xb0, 0x75, 0xcb, 0x24, 0xfb, 0x7c, 0xcf, 0xc0, 0xbd, 0x0e, 0xec, 0x16,
	0x0a, 0xbe, 0xc5, 0xd5, 0x0c, 0x23, 0x29, 0x6c, 0x96, 0x46, 0x1e, 0x1b, 0xaf, 0x15, 0xdb, 0xb9,
	0xa7, 0x2b, 0xef, 0x3f, 0xef, 0xe7, 0xd8, 0xf6, 0x07, 0x8c, 0x7e, 0x4f, 0x7a, 0xff, 0x85, 0xed,
	0x0d, 0x95, 0x5b, 0x6c, 0x1f, 0xc0, 0x6a, 0x8a, 0x85, 0x8c, 0xf3, 0x41, 0x17, 0x4b, 0x12, 0xcb,
	0x24, 0x23, 0x5e, 0x4d, 0x13, 0x58, 0x51, 0xf8, 0x99, 0x86, 0x4f, 0x93, 0x8c, 0xcc, 0x65, 0xfa,
	0x3d, 0xbb, 0x15, 0xd3, 0x00, 0x21, 0x58, 0xa0, 0x38, 0x23, 0xb6, 0x56, 0x9f, 0xd1, 0x43, 0xa8,
	0x73, 0x32, 0xc4, 0xbc, 0x6b, 0xab, 0x6d, 0xe4, 0xff, 0x76, 0x00, 0x4c, 0xad, 0xc4, 0x92, 0xa0,
	0x43, 0x58, 0x36, 0xd4, 0x63, 0xa1, 0x62, 0xf5, 0xcf, 0xa2, 0x04, 0x3f, 0x29, 0x0b, 0xd6, 0x99,
	0x56, 0xaf, 0x3e, 0x5b, 0xd1, 0x4b, 0xa2, 0x04, 0x4d, 0x55, 0x5e, 0x99, 0xaa, 0xfc, 0x2d, 0xac,
	0x4d, 0x34, 0x9b, 0x49, 0xfe, 0x1f, 0x07, 0x56, 0x0a, 0x66, 0x67, 0x82, 0x70, 0xf4, 0x71, 0xba,
	0x8e, 0xe7, 0x13, 0x3a, 0x54, 0xf6, 0x9d, 0x5a, 0x1e, 0xc1, 0x82, 0xca, 0xb3, 0xde, 0x2c, 0x0c,
	0xa2, 0xd1, 0xbb, 0x0d, 0x34, 0xbf, 0x42, 0x0e, 0x6b, 0x05, 0xe5, 0x23, 0x32, 0xd2, 0x73, 0xb7,
	0x00, 0xb4, 0xb8, 0xb8, 0x4f, 0x46, 0x46, 0xa0, 0x1b, 0xb9, 0xc2, 0x66, 0xcc, 0x4d, 0xda, 0x7f,
	0x03, 0xab, 0x7a, 0xe6, 0x07, 0x9a, 0xc8, 0x88, 0x5c, 0xe4, 0x44, 0xc8, 0x59, 0x3e, 0xa2, 0xfe,
	0x17, 0xfb, 0x28, 0x6a, 0xdc, 0x29, 0xeb, 0x13, 0x8a, 0x1e, 0x43, 0xed, 0x64, 0x48, 0x09, 0x9f,
	0xf8, 0xf6, 0x18, 0x18, 0x6d, 0x43, 0x43, 0xaa, 0xc4, 0xb8, 0xc3, 0x72, 0x2a, 0xed, 0x16, 0x40,
	0x43, 0x07, 0x0a, 0xf1, 0x7d, 0xeb, 0xd5, 0x53, 0x26, 0x71, 0xaa, 0xd6, 0x65, 0x12, 0xcd, 0x27,
	0xd3, 0x04, 0xed, 0xba, 0xfe, 0x81, 0x7c, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x66, 0xce, 0x91,
	0x85, 0xa5, 0x07, 0x00, 0x00,
}
