// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loom/plugin/plugin.proto

/*
Package plugin is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loom/plugin/plugin.proto

It has these top-level messages:
	MessageTx
	DeployTx
	CallTx
	PluginCode
*/
package plugin

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VMType int32

const (
	VMType_PLUGIN VMType = 0
	VMType_EVM    VMType = 1
)

var VMType_name = map[int32]string{
	0: "PLUGIN",
	1: "EVM",
}
var VMType_value = map[string]int32{
	"PLUGIN": 0,
	"EVM":    1,
}

func (x VMType) String() string {
	return proto.EnumName(VMType_name, int32(x))
}
func (VMType) EnumDescriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{0} }

type MessageTx struct {
	To   *types.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From *types.Address `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Data []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MessageTx) Reset()                    { *m = MessageTx{} }
func (m *MessageTx) String() string            { return proto.CompactTextString(m) }
func (*MessageTx) ProtoMessage()               {}
func (*MessageTx) Descriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{0} }

func (m *MessageTx) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MessageTx) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeployTx struct {
	VmType VMType `protobuf:"varint,1,opt,name=vm_type,json=vmType,proto3,enum=VMType" json:"vm_type,omitempty"`
	Code   []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *DeployTx) Reset()                    { *m = DeployTx{} }
func (m *DeployTx) String() string            { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()               {}
func (*DeployTx) Descriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{1} }

func (m *DeployTx) GetVmType() VMType {
	if m != nil {
		return m.VmType
	}
	return VMType_PLUGIN
}

func (m *DeployTx) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type CallTx struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *CallTx) Reset()                    { *m = CallTx{} }
func (m *CallTx) String() string            { return proto.CompactTextString(m) }
func (*CallTx) ProtoMessage()               {}
func (*CallTx) Descriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{2} }

func (m *CallTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type PluginCode struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *PluginCode) Reset()                    { *m = PluginCode{} }
func (m *PluginCode) String() string            { return proto.CompactTextString(m) }
func (*PluginCode) ProtoMessage()               {}
func (*PluginCode) Descriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{3} }

func (m *PluginCode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginCode) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageTx)(nil), "MessageTx")
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*CallTx)(nil), "CallTx")
	proto.RegisterType((*PluginCode)(nil), "PluginCode")
	proto.RegisterEnum("VMType", VMType_name, VMType_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loom/plugin/plugin.proto", fileDescriptorPlugin)
}

var fileDescriptorPlugin = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0xed, 0x36, 0xdb, 0xed, 0x39, 0x64, 0x04, 0x0f, 0x45, 0x54, 0x4a, 0x4f, 0x43, 0xb0,
	0x85, 0x09, 0x9e, 0x95, 0x29, 0x22, 0x58, 0x19, 0xa5, 0xce, 0xa3, 0x74, 0x6b, 0xac, 0xc5, 0xa6,
	0x2f, 0x34, 0xe9, 0x6c, 0xff, 0x7b, 0xe9, 0xcb, 0x4e, 0x22, 0x5e, 0xf2, 0xbe, 0xe4, 0xe5, 0x7d,
	0x3f, 0x12, 0x08, 0xf3, 0x42, 0x7f, 0x36, 0x9b, 0x60, 0x8b, 0x22, 0x2c, 0x11, 0x45, 0xc5, 0xf5,
	0x37, 0xd6, 0x5f, 0xc4, 0xa1, 0x2c, 0x9b, 0xbc, 0xa8, 0xf6, 0x25, 0x90, 0x35, 0x6a, 0x3c, 0xbd,
	0xfa, 0x6f, 0x40, 0x77, 0x92, 0x2b, 0xb3, 0x9a, 0xeb, 0xfe, 0x1b, 0x4c, 0x22, 0xae, 0x54, 0x9a,
	0xf3, 0xa4, 0x65, 0x2e, 0x0c, 0x34, 0xba, 0x96, 0x67, 0xcd, 0x8f, 0x16, 0xe3, 0xe0, 0x2e, 0xcb,
	0x6a, 0xae, 0x54, 0x3c, 0xd0, 0xc8, 0xce, 0x60, 0xf4, 0x51, 0xa3, 0x70, 0x07, 0xbf, 0x7a, 0x74,
	0xca, 0x18, 0x8c, 0xb2, 0x54, 0xa7, 0xee, 0xd0, 0xb3, 0xe6, 0xd3, 0x98, 0xd8, 0xbf, 0x85, 0xf1,
	0x3d, 0x97, 0x25, 0x76, 0x49, 0xcb, 0x3c, 0x70, 0x76, 0xe2, 0xbd, 0x8f, 0x25, 0xf9, 0xf1, 0xc2,
	0x09, 0xd6, 0x51, 0xd2, 0x49, 0x1e, 0xdb, 0x3b, 0xd1, 0xd7, 0xde, 0xb0, 0xc5, 0x8c, 0x93, 0x7f,
	0x1a, 0x13, 0xfb, 0x17, 0x60, 0x2f, 0xd3, 0xb2, 0x4c, 0x5a, 0x76, 0x02, 0x87, 0x45, 0x25, 0x1b,
	0xbd, 0x6f, 0x9b, 0x8d, 0x7f, 0x03, 0xb0, 0xa2, 0x97, 0x2f, 0x31, 0x23, 0x43, 0x95, 0x0a, 0x13,
	0x30, 0x89, 0x89, 0xff, 0x9e, 0xbb, 0x3c, 0x07, 0xdb, 0xa4, 0x33, 0x00, 0x7b, 0xf5, 0xfc, 0xfa,
	0xf8, 0xf4, 0x32, 0x3b, 0x60, 0x0e, 0x0c, 0x1f, 0xd6, 0xd1, 0xcc, 0xda, 0xd8, 0xf4, 0x31, 0xd7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x12, 0x8a, 0x63, 0x7a, 0x01, 0x00, 0x00,
}
