// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loom/plugin/plugin.proto

/*
Package plugin is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loom/plugin/plugin.proto

It has these top-level messages:
	PluginCode
*/
package plugin

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PluginCode struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *PluginCode) Reset()                    { *m = PluginCode{} }
func (m *PluginCode) String() string            { return proto.CompactTextString(m) }
func (*PluginCode) ProtoMessage()               {}
func (*PluginCode) Descriptor() ([]byte, []int) { return fileDescriptorPlugin, []int{0} }

func (m *PluginCode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginCode) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func init() {
	proto.RegisterType((*PluginCode)(nil), "PluginCode")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loom/plugin/plugin.proto", fileDescriptorPlugin)
}

var fileDescriptorPlugin = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xcf, 0xcf, 0xcd, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0x06, 0xb3, 0xf5, 0x0b, 0x72, 0x4a, 0xd3, 0x33, 0xf3, 0xa0, 0x94, 0x5e, 0x41, 0x51,
	0x7e, 0x49, 0xbe, 0x92, 0x19, 0x17, 0x57, 0x00, 0x98, 0xef, 0x9c, 0x9f, 0x92, 0x2a, 0x24, 0xc4,
	0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x89,
	0x70, 0xb1, 0x66, 0xe6, 0x15, 0x94, 0x96, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x41, 0x38,
	0x49, 0x6c, 0x60, 0xed, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0xc7, 0x9b, 0x99, 0x71,
	0x00, 0x00, 0x00,
}
