// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/loomchain/builtin/plugins/gateway/gateway.proto

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/loomchain/builtin/plugins/gateway/gateway.proto

It has these top-level messages:
	GatewayState
	FTDeposit
	NFTDeposit
	InitRequest
	ProcessEventBatchRequest
*/
package gateway

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GatewayState struct {
	LastEthBlock uint64 `protobuf:"varint,1,opt,name=last_eth_block,json=lastEthBlock,proto3" json:"last_eth_block,omitempty"`
	// TODO: These are just temporary, actual balances will be maintained by coin contracts,
	// for now this just tracks the ETH and one ERC20 balance on the Gateway
	EthBalance   *types.BigUInt `protobuf:"bytes,2,opt,name=eth_balance,json=ethBalance" json:"eth_balance,omitempty"`
	Erc20Balance *types.BigUInt `protobuf:"bytes,3,opt,name=erc20_balance,json=erc20Balance" json:"erc20_balance,omitempty"`
}

func (m *GatewayState) Reset()                    { *m = GatewayState{} }
func (m *GatewayState) String() string            { return proto.CompactTextString(m) }
func (*GatewayState) ProtoMessage()               {}
func (*GatewayState) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{0} }

func (m *GatewayState) GetLastEthBlock() uint64 {
	if m != nil {
		return m.LastEthBlock
	}
	return 0
}

func (m *GatewayState) GetEthBalance() *types.BigUInt {
	if m != nil {
		return m.EthBalance
	}
	return nil
}

func (m *GatewayState) GetErc20Balance() *types.BigUInt {
	if m != nil {
		return m.Erc20Balance
	}
	return nil
}

// Fungible Token Deposit (ETH or ERC20) made into the Gateway on Ethereum mainnet
type FTDeposit struct {
	// Token contract address, blank if ETH
	Token  *types.Address `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	From   *types.Address `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Amount *types.BigUInt `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *FTDeposit) Reset()                    { *m = FTDeposit{} }
func (m *FTDeposit) String() string            { return proto.CompactTextString(m) }
func (*FTDeposit) ProtoMessage()               {}
func (*FTDeposit) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{1} }

func (m *FTDeposit) GetToken() *types.Address {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *FTDeposit) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FTDeposit) GetAmount() *types.BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

// Non-Fungible Token Deposit (ERC721) made into the Gateway on Ethereum mainnet
type NFTDeposit struct {
	// Token contract address
	Token *types.Address `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	From  *types.Address `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Uid   *types.BigUInt `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
}

func (m *NFTDeposit) Reset()                    { *m = NFTDeposit{} }
func (m *NFTDeposit) String() string            { return proto.CompactTextString(m) }
func (*NFTDeposit) ProtoMessage()               {}
func (*NFTDeposit) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{2} }

func (m *NFTDeposit) GetToken() *types.Address {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NFTDeposit) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *NFTDeposit) GetUid() *types.BigUInt {
	if m != nil {
		return m.Uid
	}
	return nil
}

type InitRequest struct {
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{3} }

// Batch of events from the Gateway on Ethereum mainnet
type ProcessEventBatchRequest struct {
	FtDeposits  []*FTDeposit  `protobuf:"bytes,1,rep,name=ft_deposits,json=ftDeposits" json:"ft_deposits,omitempty"`
	NftDeposits []*NFTDeposit `protobuf:"bytes,2,rep,name=nft_deposits,json=nftDeposits" json:"nft_deposits,omitempty"`
}

func (m *ProcessEventBatchRequest) Reset()                    { *m = ProcessEventBatchRequest{} }
func (m *ProcessEventBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*ProcessEventBatchRequest) ProtoMessage()               {}
func (*ProcessEventBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{4} }

func (m *ProcessEventBatchRequest) GetFtDeposits() []*FTDeposit {
	if m != nil {
		return m.FtDeposits
	}
	return nil
}

func (m *ProcessEventBatchRequest) GetNftDeposits() []*NFTDeposit {
	if m != nil {
		return m.NftDeposits
	}
	return nil
}

func init() {
	proto.RegisterType((*GatewayState)(nil), "GatewayState")
	proto.RegisterType((*FTDeposit)(nil), "FTDeposit")
	proto.RegisterType((*NFTDeposit)(nil), "NFTDeposit")
	proto.RegisterType((*InitRequest)(nil), "InitRequest")
	proto.RegisterType((*ProcessEventBatchRequest)(nil), "ProcessEventBatchRequest")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/loomchain/builtin/plugins/gateway/gateway.proto", fileDescriptorGateway)
}

var fileDescriptorGateway = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0x4e, 0xab, 0x40,
	0x14, 0xc6, 0x43, 0xdb, 0xdb, 0xdc, 0x7b, 0xa0, 0x77, 0x31, 0x2b, 0xd2, 0x18, 0x43, 0x88, 0x8b,
	0x1a, 0x53, 0x68, 0xea, 0x13, 0x48, 0x6c, 0x4d, 0x37, 0xc6, 0xa0, 0xae, 0x9b, 0x01, 0x06, 0x98,
	0x00, 0x33, 0xc8, 0x1c, 0x6c, 0xfa, 0x12, 0x3e, 0xb3, 0xe1, 0x4f, 0x5b, 0x63, 0xe3, 0xce, 0x0d,
	0x9c, 0xf9, 0xbe, 0xdf, 0x39, 0xdf, 0x99, 0x0c, 0xac, 0x13, 0x8e, 0x69, 0x1d, 0x38, 0xa1, 0x2c,
	0xdc, 0x5c, 0xca, 0x42, 0x30, 0xdc, 0xc9, 0x2a, 0x6b, 0xeb, 0x30, 0xa5, 0x5c, 0xb8, 0x41, 0xcd,
	0x73, 0xe4, 0xc2, 0x2d, 0xf3, 0x3a, 0xe1, 0x42, 0xb9, 0x09, 0x45, 0xb6, 0xa3, 0xfb, 0xc3, 0xdf,
	0x29, 0x2b, 0x89, 0x72, 0xba, 0xf8, 0x61, 0x4e, 0x22, 0xe7, 0xcd, 0xd1, 0xc5, 0x7d, 0xc9, 0x54,
	0xf7, 0xed, 0x3a, 0xec, 0x0f, 0x0d, 0x8c, 0x87, 0x6e, 0xc6, 0x33, 0x52, 0x64, 0xe4, 0x0a, 0xfe,
	0xe7, 0x54, 0xe1, 0x96, 0x61, 0xba, 0x0d, 0x72, 0x19, 0x66, 0xa6, 0x66, 0x69, 0xb3, 0x91, 0x6f,
	0x34, 0xea, 0x0a, 0x53, 0xaf, 0xd1, 0xc8, 0x35, 0xe8, 0x2d, 0x40, 0x73, 0x2a, 0x42, 0x66, 0x0e,
	0x2c, 0x6d, 0xa6, 0x2f, 0xff, 0x3a, 0x1e, 0x4f, 0x5e, 0x37, 0x02, 0x7d, 0x60, 0x98, 0x7a, 0x9d,
	0x47, 0xe6, 0x30, 0x61, 0x55, 0xb8, 0x5c, 0x1c, 0xe1, 0xe1, 0x37, 0xd8, 0x68, 0xed, 0x1e, 0xb7,
	0x33, 0xf8, 0xb7, 0x7e, 0xb9, 0x67, 0xa5, 0x54, 0x1c, 0xc9, 0x25, 0xfc, 0x41, 0x99, 0x31, 0xd1,
	0xee, 0xd0, 0xf4, 0xdc, 0x45, 0x51, 0xc5, 0x94, 0xf2, 0x3b, 0x99, 0x5c, 0xc0, 0x28, 0xae, 0x64,
	0x71, 0xcc, 0x3f, 0xd8, 0xad, 0x4a, 0x2c, 0x18, 0xd3, 0x42, 0xd6, 0x02, 0xcf, 0x22, 0x7b, 0xdd,
	0x8e, 0x01, 0x1e, 0x7f, 0x2b, 0x6d, 0x0a, 0xc3, 0x9a, 0x47, 0x67, 0x51, 0x8d, 0x68, 0x4f, 0x40,
	0xdf, 0x08, 0x8e, 0x3e, 0x7b, 0xab, 0x99, 0x42, 0x7b, 0x07, 0xe6, 0x53, 0x25, 0x43, 0xa6, 0xd4,
	0xea, 0x9d, 0x09, 0xf4, 0x28, 0x86, 0x69, 0xef, 0x91, 0x1b, 0xd0, 0x63, 0xdc, 0x46, 0xdd, 0x4a,
	0xca, 0xd4, 0xac, 0xe1, 0x4c, 0x5f, 0x82, 0x73, 0xdc, 0xd2, 0x87, 0x18, 0xfb, 0x52, 0x11, 0x07,
	0x0c, 0xf1, 0x95, 0x1e, 0xb4, 0xb4, 0xee, 0x9c, 0x2e, 0xe5, 0xeb, 0xe2, 0xc4, 0x07, 0xe3, 0xf6,
	0xd1, 0x6f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x00, 0x28, 0x78, 0x7a, 0x70, 0x02, 0x00, 0x00,
}
