[[TestCases]]
  RunCmd = "{{ $.LoomPath }} dpos3 list-validators"
  Condition = "excludes"
  Excluded = ["Error"]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg config"
  Condition = "excludes"
  Excluded = ["Error", "RPC error"]

# app.db cloning will take place at block 10, so wait until that happens...
[[TestCases]]
  RunCmd = "wait_for_block_height_to_reach 0 12"

# kill node 1 for 1s, it will swap out the app.db on restart
[[TestCases]]
  RunCmd = "kill_and_restart_node 1 1"

# wait for node 1 to catch up
[[TestCases]]
  RunCmd = "wait_for_node_to_catch_up 1"

# send through a tx, doesn't matter what it does, just need to change app state
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} dpos3 change-fee 2000 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Excluded = ["Error", "RPC error"]

# make sure node 1 keeps up over the next 2 blocks
[[TestCases]]
  RunCmd = "wait_for_block_height_to_increase 1 2"

# kill node 1 again for 1s, it will not swap out the app.db this time
[[TestCases]]
  RunCmd = "kill_and_restart_node 1 1"

# wait for node 1 to catch up
[[TestCases]]
  RunCmd = "wait_for_node_to_catch_up 1"

# send through another tx to change app state
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} dpos3 change-fee 3000 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Excluded = ["Error", "RPC error"]

# make sure node 1 keeps up over the next 2 blocks
[[TestCases]]
  RunCmd = "wait_for_block_height_to_increase 1 2"

[[TestCases]]
  RunCmd = "checkapphash"