[[TestCases]]
  RunCmd = "blueprint-cli call create-acct -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["created successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call create-acct -u user2 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ["created successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call create-acct -u user3 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["created successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1000 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 9999 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 9999 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 12345 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 12345 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 87777 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 87777 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 09990 -k {{index $.AccountPrivKeyPathList 0}}"
  # Condition = "contains"
  # Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 87777 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 10009 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 10009 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 20000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  # Iterations = 4
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 20000 from user 'user1'"]

  [[TestCases]]
  RunCmd = "blueprint-cli call create-acct -u user2 -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ["created successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call create-acct -u user3 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["created successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1000 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 9999 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 9999 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 12345 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 12345 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 87777 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 87777 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 09990 -k {{index $.AccountPrivKeyPathList 0}}"
  # Condition = "contains"
  # Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 87777 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 1 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 10009 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["successfully"]

[[TestCases]]
  RunCmd = "blueprint-cli call get -u user1 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["get value 10009 from user 'user1'"]

[[TestCases]]
  RunCmd = "blueprint-cli call set -u user1 -v 20000 -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Iterations = 10
  Expected = ["successfully"]