ReceiptsVersion: 2
DPOSVersion: 2
ChainConfig: 
  ContractEnabled: true
  EnableFeatureStartupDelay: 5
  EnableFeatureInterval: 15
ContractLogLevel: "debug"
LoomLogLevel: "debug"
AppStore:
  Version: 3
  SaveEVMStateToIAVL: false
CachingStore:
  CachingEnabled: true