[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin transfer {{index $.AccountAddressList 1}} 20000000 -k {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["120000000000000000000"]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["800000000000000000"]