[[TestCases]]
  Dir = ""
  All = true
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 2}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 2 contracts",
    "not authorized to deploy Go contract, deploying contact coin",
    "not authorized to deploy Go contract, deploying contact dposV3",
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"coin\",\"location\":\"coin:1.0.0\",\"init\":null},{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"dposV3\",\"location\":\"dposV3:3.0.0\",\"init\":{\"params\":{\"validatorCount\":\"21\",\"electionCycleLength\":\"604800\"},\"validators\":[{\"pubKey\":\"3ZUdeKaVH+mcYMOjp85EAOiGLhgfo5Wd8HWv/sr6FWI=\",\"power\":\"10\"}]}}]}\" }" }
  ]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 2 contracts",
    "Contract coin deployed to address",
    "Contract dposV3 deployed to address",
    "2 contract(s) successfully deployed"
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"coin\",\"location\":\"coin:1.0.0\",\"init\":null},{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"dposV3\",\"location\":\"dposV3:3.0.0\",\"init\":{\"params\":{\"validatorCount\":\"21\",\"electionCycleLength\":\"604800\"},\"validators\":[{\"pubKey\":\"3ZUdeKaVH+mcYMOjp85EAOiGLhgfo5Wd8HWv/sr6FWI=\",\"power\":\"10\"}]}}]}\" }" }
  ]

[[TestCases]]
All = true
RunCmd = "{{ $.LoomPath }} contract coin"
Condition = "contains"
Expected = ["Name","Address","Owner","coin"]
