[[TestCases]]
  RunCmd = "loom deployer list-deployers"
  Condition = "contains"
  Expected = ['BOTH', 'EVM']

[[TestCases]]
  RunCmd = "loom deployer add-deployer 0x5cecd1f7261e1f4c684e297be3edf03b825e01c4 go -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom deployer add-deployer 0x5cecd1f7261e1f4c684e297be3edf03b825e01c4 go -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['deployer already exists']

[[TestCases]]
  RunCmd = "loom deployer list-deployers"
  Condition = "contains"
  Expected = ['XOzR9yYeH0xoTil74+3wO4JeAcQ=']

[[TestCases]]
  RunCmd = "loom deployer add-deployer 0x7aecd1f7261e1f4c684e297be3edf03b825e01c4 go -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['not authorized']

[[TestCases]]
  RunCmd = "loom deployer get-deployer 0x5cecd1f7261e1f4c684e297be3edf03b825e01c4 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['XOzR9yYeH0xoTil74+3wO4JeAcQ=','GO']

[[TestCases]]
  RunCmd = "loom deployer remove-deployer 0x7aecd1f7261e1f4c684e297be3edf03b825e01c4 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['not authorized']

[[TestCases]]
  RunCmd = "loom deployer remove-deployer 0x5cecd1f7261e1f4c684e297be3edf03b825e01c4 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "loom deployer get-deployer 0x5cecd1f7261e1f4c684e297be3edf03b825e01c4 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['deployer does not exist']

[[TestCases]]
  RunCmd = "loom deployer list-deployers"
  Condition = "contains"
  Expected = ['BOTH', 'EVM']
