[[TestCases]]
  RunCmd = "/usr/bin/curl -X POST --data {\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83} {{index $.NodeProxyAppAddressList 0}}/eth"
  All = true
  Condition = "contains"
  Expected = [
                "\"result\": \"0x",
                "\"jsonrpc\": \"2.0\",",
                "\"id\": 83"
             ]

# Test batch requests
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data [{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83},{"jsonrpc":"2.0","method":"eth_blockNumber","params":["invalid"],"id":83},{"jsonrpc":"2.0","method":"eth_getBalance","params":[],"id":83}] {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
        '"result": "0x1"',
        '"error":',
        '"code": -32602',
        '"result": "0x0"'
  ]