# First block 0x0.
# pending block not implemented yet
# "latest" as block number input should fail as there is no latest block.

# Perform a go-transaction
[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin transfer {{index $.AccountAddressList 1}} 20000000 -k {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""
  Delay = 500

[[TestCases]]
  RunCmd = "wait_for_block_height_to_reach 0 3"

# eth_getBlockByNumber returns a transaction in transaction list
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x3",true],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
    '"transactionIndex": "0x0"',
    '"input": "0x080110011a3c0a085472616e7366657212300a1f0a0764656661756c741214'
  ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x2",true],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [ '"transactions": [],' ]

[[TestCases]]
  RunCmd = "wait_for_block_height_to_reach 0 3"

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByNumber","params":["0x3"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [ '"result": "0x1",'  ]