[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
                '"result": "0x',
                '"jsonrpc": "2.0"',
                '"id": 83'
             ]
