# First block 0x0.
# pending block not implemented yet
# "latest" as block number input should fail as there is no latest block.

# Perform a transaction
[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} coin transfer {{index $.AccountAddressList 1}} 20000000 -k {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""
  Delay = 500

# eth_getBlockByNumber returns a transaction in transaction list
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x3",true],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
    "transactionIndex",
    "input"
  ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x3",true],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "excludes"
  Expected = [
    '"transactions": [],'
  ]