[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma get-sources"
  Condition = "contains"
  Expected = [
                '"name": "sms"',
                '"reward": "1"',
                '"name": "oauth"',
                '"reward": "3"',
                '"name": "token"',
                '"reward": "4"',
                '"name": "coin-deploy"',
                '"reward": "1"',
                '"target": "DEPLOY"',
                '"name": "award-deploy"',
             ]

 [[TestCases]]
   RunCmd = "{{ $.LoomPath }} karma reset-sources fred 3 CALL mary 5 CALL chris 7 DEPLOY -k {{index $.AccountPrivKeyPathList 1}}"
   Condition = "contains"
   Expected = [
                 "Error: call contract",
              ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma reset-sources alpha 3 CALL beta 5 CALL gamma 7 DEPLOY -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "sources successfully updated",
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma get-sources"
  Condition = "contains"
  Expected = [
                '"name": "alpha"',
                '"reward": "3"',
                '"name": "beta"',
                '"reward": "5"',
                '"name": "gamma"',
                '"reward": "7"',
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma add-karma default:{{index $.AccountAddressList 2}} alpha 1 beta 2 -k {{index $.AccountPrivKeyPathList 0}}"
  Expected = [
                "user's sources successfully updated",
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma get-user-state default:{{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = [
                '"name": "alpha",',
                '"Value": 1',
                '"name": "beta"',
                '"Value": 2',
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma get-total default:{{index $.AccountAddressList 2}} CALL"
  Condition = "contains"
  Expected = [ '"Value": 13' ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma delete-sources-for-user {{index $.AccountAddressList 2}} alpha -k {{index $.AccountPrivKeyPathList 1}}"
  Expected = [
                "Oracle unverified",
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma update-oracle default:{{index $.AccountAddressList 1}} -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "oracle changed",
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma delete-sources-for-user {{index $.AccountAddressList 2}} alpha -k {{index $.AccountPrivKeyPathList 1}}"
  Expected = [
                "user's sources successfully updated",
             ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} karma get-user-state {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = [
                '"name": "beta"',
                '"Value": 2',
             ]