[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "contains"
  Expected = ['deploytx:v1.1']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "named evm contracts are not allowed",
             ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i inputSet987.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "name is not registered"
             ]
  Datafiles = [
    { Filename = "inputSet987.bin", Contents = "60fe47b100000000000000000000000000000000000000000000000000000000000003db" }
  ]


[[TestCases]]
  RunCmd = "{{ $.LoomPath }} static-call-evm -i inputGet.bin -n SimpleStore"
  Condition = "contains"
  Expected = [
               "name is not registered"
             ]
  Datafiles = [
    { Filename = "inputGet.bin", Contents = "6d4ce63c" }
  ]

  [[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 1 contracts",
    "Contract SimpleStore deployed to address",
    "1 contract(s) successfully deployed"
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"SimpleStore\",\"location\":\"coin:1.0.0\",\"init\":null}]}"}
  ]

