// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: loom/loom.proto

/*
Package loom is a generated protocol buffer package.

It is generated from these files:
	loom/loom.proto

It has these top-level messages:
	Address
	Transaction
	Signer
	SignedTx
	DummyTx
*/
package loom

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Local   []byte `protobuf:"bytes,2,opt,name=local,proto3" json:"local,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptorLoom, []int{0} }

func (m *Address) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Address) GetLocal() []byte {
	if m != nil {
		return m.Local
	}
	return nil
}

type Transaction struct {
	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inner []byte `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorLoom, []int{1} }

func (m *Transaction) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

type Signer struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *Signer) Reset()                    { *m = Signer{} }
func (m *Signer) String() string            { return proto.CompactTextString(m) }
func (*Signer) ProtoMessage()               {}
func (*Signer) Descriptor() ([]byte, []int) { return fileDescriptorLoom, []int{2} }

func (m *Signer) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signer) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type SignedTx struct {
	Inner   []byte    `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Signers []*Signer `protobuf:"bytes,2,rep,name=signers" json:"signers,omitempty"`
}

func (m *SignedTx) Reset()                    { *m = SignedTx{} }
func (m *SignedTx) String() string            { return proto.CompactTextString(m) }
func (*SignedTx) ProtoMessage()               {}
func (*SignedTx) Descriptor() ([]byte, []int) { return fileDescriptorLoom, []int{3} }

func (m *SignedTx) GetInner() []byte {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *SignedTx) GetSigners() []*Signer {
	if m != nil {
		return m.Signers
	}
	return nil
}

type DummyTx struct {
	Val string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DummyTx) Reset()                    { *m = DummyTx{} }
func (m *DummyTx) String() string            { return proto.CompactTextString(m) }
func (*DummyTx) ProtoMessage()               {}
func (*DummyTx) Descriptor() ([]byte, []int) { return fileDescriptorLoom, []int{4} }

func (m *DummyTx) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *DummyTx) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*Signer)(nil), "Signer")
	proto.RegisterType((*SignedTx)(nil), "SignedTx")
	proto.RegisterType((*DummyTx)(nil), "DummyTx")
}

func init() { proto.RegisterFile("loom/loom.proto", fileDescriptorLoom) }

var fileDescriptorLoom = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x87, 0xcb, 0xfa, 0x36, 0x7f, 0x10, 0x3c, 0x54, 0x50, 0xa8, 0x39, 0xf5, 0xe2,
	0x04, 0x77, 0xf3, 0x26, 0xea, 0x41, 0xbc, 0xc5, 0xde, 0x47, 0xd6, 0x84, 0xf9, 0x30, 0x4d, 0x46,
	0xd2, 0xca, 0xfa, 0xdf, 0x4b, 0xd2, 0x96, 0x79, 0x09, 0xef, 0xfb, 0x85, 0xcf, 0xfb, 0x90, 0x07,
	0x97, 0xda, 0xda, 0xe6, 0x31, 0x3c, 0xeb, 0x83, 0xb3, 0xad, 0x65, 0xcf, 0x40, 0x5e, 0xa4, 0x74,
	0xca, 0x7b, 0x7a, 0x03, 0x8b, 0xfa, 0x5b, 0xa0, 0xd9, 0xa2, 0xcc, 0x93, 0x22, 0x29, 0x33, 0x4e,
	0x62, 0xfe, 0x90, 0xf4, 0x1a, 0xce, 0xb4, 0xad, 0x85, 0xce, 0xd3, 0x22, 0x29, 0x57, 0x7c, 0x08,
	0x6c, 0x03, 0xcb, 0xca, 0x09, 0xe3, 0x45, 0xdd, 0xa2, 0x35, 0xf4, 0x02, 0xd2, 0x91, 0x3c, 0xe7,
	0x29, 0x46, 0x08, 0x8d, 0x51, 0x6e, 0x82, 0x62, 0x60, 0xef, 0x30, 0xff, 0xc2, 0xbd, 0x51, 0x8e,
	0xde, 0x42, 0xe6, 0x71, 0x6f, 0x44, 0xdb, 0x39, 0x15, 0xb1, 0x15, 0x3f, 0x15, 0xf4, 0x0e, 0xe0,
	0xd0, 0xed, 0x34, 0xd6, 0xdb, 0x1f, 0xd5, 0x8f, 0x2b, 0xb2, 0xa1, 0xf9, 0x54, 0x3d, 0x7b, 0x85,
	0x45, 0x5c, 0x23, 0xab, 0xe3, 0x49, 0x94, 0xfc, 0x13, 0xd1, 0x7b, 0x20, 0x3e, 0x8a, 0x7c, 0x9e,
	0x16, 0xb3, 0x72, 0xf9, 0x44, 0xd6, 0x83, 0x98, 0x4f, 0x3d, 0x7b, 0x00, 0xf2, 0xd6, 0x35, 0x4d,
	0x5f, 0x1d, 0xe9, 0x15, 0xcc, 0x7e, 0x85, 0x1e, 0xff, 0x1d, 0xc6, 0xd0, 0x4c, 0xe6, 0x8c, 0x87,
	0x71, 0x37, 0x8f, 0x27, 0xdb, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x17, 0xb6, 0x5f, 0x8d, 0x45,
	0x01, 0x00, 0x00,
}
